### ISSUE TITLE
[JOSS Review] Automated tests

### ISSUE THREAD

**Issue by HubLot** [gpantel/MolPainter#15]
This issue is part of the JOSS review process available here: https://github.com/openjournals/joss-reviews/issues/5128

---

According to [JOSS review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html#tests):

      Authors are strongly encouraged to include an automated test suite covering the core functionality of their software.

As far as I can tell, MolPainter does not contain any automated or manual tests. I strongly encourage to include tests, at least for the drawing part (to make sure the system is correctly created with lipids and/or solute) and for Molsolvator (to make sure the solvation process is  running smoothly).

The [pytest](https://docs.pytest.org/en/7.2.x/) testing framework is a good tool to implement those kind of tests. Additionally, once they are implemented, it would be useful to run those tests automatically through a continuous integration service like [Github Actions](https://docs.github.com/en/actions).

**Comment by gpantel** [comment]
We have added manual tests for molpainter that can be run with python -m pytest. The test for MolPainter checks if it can properly load a JSON file. The test for MolSolvator checks if it can properly reproduce a solvent box given an initial seed for the RNG.

**Comment by HubLot** [comment]
Thanks for the tests although it's quit minimalist.
In Molpainter, the exporter needs to be tested to make sure the PDB produced is correct compared to the GUI grid, same thing for the JSON save file and the solute feature.

**Comment by gpantel** [comment]
Yeah, we planned to add tests of that nature in 1.1.4. Thanks for suggesting specifics.

**Comment by HubLot** [comment]
okay.
