### ISSUE TITLE
[JOSS Review] MolPainter tool minor improvements

### ISSUE THREAD

**Issue by HubLot** [gpantel/MolPainter#19]
This issue is part of the JOSS review process available here: https://github.com/openjournals/joss-reviews/issues/5128

---

Overall, the GUI based Molpainter tool is a good piece of work. The GUI is stable and the interaction is smoothed.
I have only minor suggestions:
   - add a "about" button with version number, link to the documentation and to the GitHub repository. This will allow users to easily find useful information,= and documentation about the software.
   - Rename "Open Painting" by "Load Painting". It will be clearer for the users that this button is for "loading" a configuration file and not "opening" a random file.
   - When using the pencil painting tool, is it possible to paint one cell by just clicking on it and not clicking and dragging? This will make easier to paint tiny cells.
   - The % of molecules printed on the left is independent of the number of cells labeled "empty". Wouldn't it be better that the sum of all percentage represent the total surface of the layer and thus, taking into account the *empty* cells ?

**Comment by gpantel** [comment]
Thank you for the helpful suggestions!

1) We have added an "About" button with important links to the software and documentation.
2) We have renamed "Open Painting" to "Load Painting".
3) Now you can click or hold to use the pencil tool.
4) The mol% is a volume-independent measure of the relative quantity of chemical species in a system. Typically in lipid bilayers, which is the main application for MolPainter, mol% is used to measure the relative amount of lipids and other molecules in a layer, so we'll keep it as-is.

**Comment by HubLot** [comment]
Thanks for addressing the comments.
For the 4., thanks for the explanation, I think it would be useful to have this in the "Molecules" section of the README.md.

**Comment by gpantel** [comment]
Thanks for the quick reply. I added (4) to the docs/README.md.

**Comment by HubLot** [comment]
thanks
