### ISSUE TITLE
[JOSS Review]  The text "Layer #" do not show up for the active layer

### ISSUE THREAD

**Issue by arkajitmandal** [gpantel/MolPainter#21]
When first loading the software the text "Layer 1" is not shown. 
<img width="346" alt="Screenshot 2023-02-20 at 9 03 08 PM" src="https://user-images.githubusercontent.com/10487689/220229143-9378e53f-a7e2-4d6c-8816-cf56ed56a4cb.png">
It shows up when right clicking on the tab,

<img width="559" alt="Screenshot 2023-02-20 at 9 11 01 PM" src="https://user-images.githubusercontent.com/10487689/220229988-9af096e4-5c22-40fe-b266-6b67e442cb60.png">

On closer inspection the issue seems to that the active/on-click color of text for buttons is chosen to be white, thus making it disappear if the button background is white. 
<img width="471" alt="Screenshot 2023-02-20 at 9 15 44 PM" src="https://user-images.githubusercontent.com/10487689/220230572-5819f8f1-53ab-414b-a51d-21cb432d5567.png">

To me, an easy fix it to swap the color white for the button/tab background for Layers to something dark.

**Comment by gpantel** [comment]
Thank you for reporting this.

This is a known issue on Mac OS Monterey (https://docs.python.org/3.10/whatsnew/changelog.html#id71). The solution is to update to python 3.10 or higher.

**Comment by arkajitmandal** [comment]
okay. Thats fair!
