### ISSUE TITLE
Cited author name appearing as "first mi last year" rather than "last year" in built PDF.

### ISSUE THREAD

**Issue by gpantel** [gpantel/MolPainter#23]
In all instances where there is a citation to "Pantelopulos, George A" the built PDF of the manuscript is showing "George A. Pantelopulos". Based on the BIB file I am unsure what might possibly be causing this, but I assume this is not the intended behavior. Is this the intended behavior?

**Comment by jgostick** [comment]
This is odd behavior for sure. I am not a bibtex expert, but I did notice one trend.  The letters "OR" are in your name, and it seems that the bibtex parser is treating "AND" specially, so maybe the OR is interferring with something. I also checked that the only other instances of people with OR in their names are not first authors.  Anyway, this is pure guessing.  I will ask one of the more experienced editors if they have any clues.

**Comment by gpantel** [comment]
Ah, ok! Removing my first name from the BIB file avoids the issue. Perhaps it's just the scenario you proposed. Should be ok for now.

**Comment by jgostick** [comment]
I have started a thread on the JOSS slack channel.  You deserve to have your first name in the bibliography (altough there are probably no a lot of G A Pantelopulos's I'm guessing?), so let's see what the experts think.  Besides, we should fix this bug properly.

**Comment by gpantel** [comment]
Thank you! If this is a bug perhaps it should be opened as an issue in JOSS? At least as far as internet searches of the day are concerned I don't know of an other G A Pantelopulos.
